"""How a model came to exist: the run, the checkpoint, and the derivation.

`ai/training.py` answers what a model was trained *on* — the corpus closure, and the
bill of materials that follows from it. This package answers the three questions
that sit either side of that one:

- **`experiments`** — the run itself. Hyperparameters, sweeps, ablations, and the
  scaling-law fit that argued for the compute. When a model regresses, the first
  question is what changed since the last run, and four different causes have four
  different remedies.
- **`checkpoints`** — the artefact mid-flight. Sharding, parallelism topology, and
  whether a job can actually resume from one, which is a real operation with a real
  failure mode that a single opaque blob cannot express.
- **`finetuning`** — everything downstream of a base model. Adapters, merges,
  distillation, quantization, and the preference data that has annotators in it.

The common thread is that each of these is a *dataset* with its own inputs, so the
graph, the planner, and the eraser already work on them. Nothing here needs a second
lineage system.
"""

from .checkpoints import (
    Checkpoint,
    Parallelism,
    ResumeVerdict,
    RetentionPlan,
    RetentionReason,
    Shard,
    ShardingScheme,
    can_resume,
    checkpoint_size,
    compatible_topologies,
    describe_topology,
    missing_shards,
    optimizer_overhead,
    parallelism_from,
    reshard_plan,
    retention_plan,
    validate,
    world_size,
)
from .experiments import (
    Ablation,
    DeterminismReport,
    HyperparameterDiff,
    Run,
    RunComparison,
    RunStatus,
    ScalingLaw,
    Sweep,
    Trial,
    best_trial,
    chinchilla_optimal,
    compare,
    compute_flops,
    determinism_report,
    diff_hyperparameters,
    fit_scaling_law,
    gpu_hours,
    is_regression,
    loss_curve_summary,
    pareto_front,
    predict_tokens_needed,
    run_edges,
    sweep_summary,
    throughput,
)
from .finetuning import (
    Adaptation,
    AdaptationKind,
    Annotator,
    Derivation,
    Distillation,
    Merge,
    PreferencePair,
    PreferenceSet,
    Quantization,
    QuantizationFormat,
    adapter_edges,
    annotator_diversity,
    base_of,
    derivation_chain,
    distillation_edges,
    effective_restrictions,
    inter_annotator_agreement,
    is_derived_from,
    lineage_depth,
    merge_edges,
    preference_edges,
    quantization_edges,
    rank_stability,
    trainable_fraction,
    validate_merge,
)

__all__ = [
    "Ablation",
    "Adaptation",
    "AdaptationKind",
    "Annotator",
    "Checkpoint",
    "Derivation",
    "DeterminismReport",
    "Distillation",
    "HyperparameterDiff",
    "Merge",
    "Parallelism",
    "PreferencePair",
    "PreferenceSet",
    "Quantization",
    "QuantizationFormat",
    "ResumeVerdict",
    "RetentionPlan",
    "RetentionReason",
    "Run",
    "RunComparison",
    "RunStatus",
    "ScalingLaw",
    "Shard",
    "ShardingScheme",
    "Sweep",
    "Trial",
    "adapter_edges",
    "annotator_diversity",
    "base_of",
    "best_trial",
    "can_resume",
    "checkpoint_size",
    "chinchilla_optimal",
    "compare",
    "compatible_topologies",
    "compute_flops",
    "derivation_chain",
    "describe_topology",
    "determinism_report",
    "diff_hyperparameters",
    "distillation_edges",
    "effective_restrictions",
    "fit_scaling_law",
    "gpu_hours",
    "inter_annotator_agreement",
    "is_derived_from",
    "is_regression",
    "lineage_depth",
    "loss_curve_summary",
    "merge_edges",
    "missing_shards",
    "optimizer_overhead",
    "parallelism_from",
    "pareto_front",
    "predict_tokens_needed",
    "preference_edges",
    "quantization_edges",
    "rank_stability",
    "reshard_plan",
    "retention_plan",
    "run_edges",
    "sweep_summary",
    "throughput",
    "trainable_fraction",
    "validate",
    "validate_merge",
    "world_size",
]
