"""How a model came to exist: the run, the checkpoint, and the derivation.

`ai/training.py` answers what a model was trained *on* — the corpus closure, and the
bill of materials that follows from it. This package answers the three questions
that sit either side of that one:

- **`experiments`** — the run itself. Hyperparameters, sweeps, ablations, and the
  scaling-law fit that argued for the compute. When a model regresses, the first
  question is what changed since the last run, and four different causes have four
  different remedies.
- **`checkpoints`** — the artefact mid-flight. Sharding, parallelism topology, and
  whether a job can actually resume from one, which is a real operation with a real
  failure mode that a single opaque blob cannot express.
- **`finetuning`** — everything downstream of a base model. Adapters, merges,
  distillation, quantization, and the preference data that has annotators in it.

The common thread is that each of these is a *dataset* with its own inputs, so the
graph, the planner, and the eraser already work on them. Nothing here needs a second
lineage system.
"""

from .checkpoints import (
    Checkpoint,
    Parallelism,
    ResumeVerdict,
    RetentionPlan,
    RetentionReason,
    Shard,
    ShardingScheme,
    can_resume,
    checkpoint_size,
    compatible_topologies,
    describe_topology,
    missing_shards,
    optimizer_overhead,
    parallelism_from,
    reshard_plan,
    retention_plan,
    validate,
    world_size,
)
from .experiments import (
    Ablation,
    DeterminismReport,
    HyperparameterDiff,
    Run,
    RunComparison,
    RunStatus,
    ScalingLaw,
    Sweep,
    Trial,
    best_trial,
    chinchilla_optimal,
    compare,
    compute_flops,
    determinism_report,
    diff_hyperparameters,
    fit_scaling_law,
    gpu_hours,
    is_regression,
    loss_curve_summary,
    pareto_front,
    predict_tokens_needed,
    run_edges,
    sweep_summary,
    throughput,
)
from .finetuning import (
    Adaptation,
    AdaptationKind,
    Annotator,
    Derivation,
    Distillation,
    Merge,
    PreferencePair,
    PreferenceSet,
    Quantization,
    QuantizationFormat,
    adapter_edges,
    annotator_diversity,
    base_of,
    derivation_chain,
    distillation_edges,
    effective_restrictions,
    inter_annotator_agreement,
    is_derived_from,
    lineage_depth,
    merge_edges,
    preference_edges,
    quantization_edges,
    rank_stability,
    trainable_fraction,
    validate_merge,
)
from .mixtures import (
    Component,
    EpochPressure,
    Mixture,
    RemixPlan,
    WeightChange,
    component_edges,
    effective_epochs,
    epoch_pressure,
    mixture_edges,
    normalize,
    remix_plan,
    token_budget,
    unattributed,
    untested,
)
from .mixtures import validate as validate_mixture
from .tokenizers import (
    BudgetVerdict,
    CorpusEstimate,
    Fertility,
    Tokenizer,
    VocabularyDiff,
    budget_check,
    compatible,
    diff,
    fertility,
    fertility_by_language,
    is_superset,
    reestimate,
    special_token_conflicts,
    tokenizer_edges,
    vocabulary_overlap,
    worst_language,
)

__all__ = [
    "Ablation",
    "Adaptation",
    "AdaptationKind",
    "Annotator",
    "BudgetVerdict",
    "Checkpoint",
    "Component",
    "CorpusEstimate",
    "Derivation",
    "DeterminismReport",
    "Distillation",
    "EpochPressure",
    "Fertility",
    "HyperparameterDiff",
    "Merge",
    "Mixture",
    "Parallelism",
    "PreferencePair",
    "PreferenceSet",
    "Quantization",
    "QuantizationFormat",
    "RemixPlan",
    "ResumeVerdict",
    "RetentionPlan",
    "RetentionReason",
    "Run",
    "RunComparison",
    "RunStatus",
    "ScalingLaw",
    "Shard",
    "ShardingScheme",
    "Sweep",
    "Tokenizer",
    "Trial",
    "VocabularyDiff",
    "WeightChange",
    "adapter_edges",
    "annotator_diversity",
    "base_of",
    "best_trial",
    "budget_check",
    "can_resume",
    "checkpoint_size",
    "chinchilla_optimal",
    "compare",
    "compatible",
    "compatible_topologies",
    "component_edges",
    "compute_flops",
    "derivation_chain",
    "describe_topology",
    "determinism_report",
    "diff",
    "diff_hyperparameters",
    "distillation_edges",
    "effective_epochs",
    "effective_restrictions",
    "epoch_pressure",
    "fertility",
    "fertility_by_language",
    "fit_scaling_law",
    "gpu_hours",
    "inter_annotator_agreement",
    "is_derived_from",
    "is_regression",
    "is_superset",
    "lineage_depth",
    "loss_curve_summary",
    "merge_edges",
    "missing_shards",
    "mixture_edges",
    "normalize",
    "optimizer_overhead",
    "parallelism_from",
    "pareto_front",
    "predict_tokens_needed",
    "preference_edges",
    "quantization_edges",
    "rank_stability",
    "reestimate",
    "remix_plan",
    "reshard_plan",
    "retention_plan",
    "run_edges",
    "special_token_conflicts",
    "sweep_summary",
    "throughput",
    "token_budget",
    "tokenizer_edges",
    "trainable_fraction",
    "unattributed",
    "untested",
    "validate",
    "validate_mixture",
    "validate_merge",
    "vocabulary_overlap",
    "world_size",
    "worst_language",
]
