"""Schedules as the file your orchestrator already reads.

`graph.plan.schedule` produces the structure — waves, batches, dependencies — and
`to_task_list` hands it over as data. That is the right seam and it leaves one step
to the user, which in practice is the step where a good plan stops being used: the
person who wanted incremental rebuilds now has to write and maintain a translation
layer, and the translation layer drifts.

So this module generates the DAG file itself, for the three orchestrators that cover
most of the field.

**Generated, not executed.** Every function here returns a string. Nothing imports
Airflow, Dagster, or Prefect — a library that pulls in an orchestrator to be imported
is a library people vendor around, and `fathom` already refuses that for `click`. The
output is a file you commit and read, not a runtime binding.

**Two properties the generated files keep**, because a DAG that loses either is worse
than no DAG:

- **Wave boundaries are dependencies, not ordering hints.** Wave *n+1* depends on
  every task in wave *n*. Emitting them as a sequence an orchestrator is free to
  reinterpret is how a downstream table gets rebuilt from an upstream one that has
  not been written yet.
- **Partition keys travel with the task.** A task that says "rebuild gold.monthly"
  without saying which partitions has thrown away the entire point, and will quietly
  full-rebuild.

**What is deliberately not here.** No scheduling interval, no retry policy, no alerting
config, no connection ids. Those are decisions about *your* platform that a generator
guessing at them would get wrong in a way that looks authoritative. The generated file
is a starting point with a header saying so.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from ..graph.plan.schedule import Schedule, to_task_list

__all__ = [
    "GeneratedTask",
    "tasks_of",
    "to_airflow",
    "to_dagster",
    "to_prefect",
    "write_dag",
]


@dataclass(frozen=True)
class GeneratedTask:
    """One task in a generated DAG.

    `to_task_list` returns plain mappings, which is right for JSON and awkward for a
    generator that indexes them a dozen times. This is the same data with names, so a
    typo is a type error rather than a `KeyError` in someone's Airflow parse step.
    """

    id: str
    dataset: str
    partitions: tuple[str, ...]
    depends_on: tuple[str, ...]

    def shell(self, command: str) -> str:
        """The rebuild invocation, with the partition keys that are the whole point."""
        keys = " ".join(f"'{k}'" for k in self.partitions)
        return f"{command} '{self.dataset}' --partitions {keys}"


def tasks_of(plan: Schedule) -> list[GeneratedTask]:
    """The schedule as typed tasks, in dependency order."""
    return [
        GeneratedTask(
            id=raw["id"],
            dataset=raw["dataset"],
            partitions=tuple(raw["partitions"]),
            depends_on=tuple(raw["depends_on"]),
        )
        for raw in to_task_list(plan)
    ]


_HEADER = (
    "# Generated by fathom from a partition-scoped rebuild plan.\n"
    "# Wave boundaries are real dependencies, not ordering hints — reordering them\n"
    "# rebuilds a downstream table from an upstream one that has not been written.\n"
    "# Intervals, retries, alerting, and connections are deliberately absent: those\n"
    "# are decisions about your platform, and a generator guessing at them would be\n"
    "# wrong in a way that looks authoritative.\n"
)


def _quote(value: str) -> str:
    """Python string literal. Uses `json.dumps` so quotes and backslashes escape."""
    return json.dumps(value)


def to_airflow(
    plan: Schedule,
    *,
    dag_id: str = "fathom_rebuild",
    command: str = "fathom rebuild",
    operator: str = "BashOperator",
) -> str:
    """An Airflow DAG file.

    `BashOperator` by default because it is the one operator every deployment has and
    the one whose behaviour is obvious from the generated line. Swap `operator` if you
    have a house wrapper; the import is generated to match.
    """
    tasks = tasks_of(plan)
    lines = [
        _HEADER,
        "from airflow import DAG",
        f"from airflow.operators.bash import {operator}",
        "",
        f"with DAG({_quote(dag_id)}, schedule=None, catchup=False) as dag:",
    ]
    if not tasks:
        lines.append("    pass  # nothing to rebuild")
        return "\n".join(lines) + "\n"

    for task in tasks:
        lines.append(f"    {task.id} = {operator}(")
        lines.append(f"        task_id={_quote(task.id)},")
        lines.append(f"        bash_command={_quote(task.shell(command))},")
        lines.append("    )")

    lines.append("")
    for task in tasks:
        for upstream in task.depends_on:
            lines.append(f"    {upstream} >> {task.id}")
    return "\n".join(lines) + "\n"


def to_dagster(
    plan: Schedule, *, job_name: str = "fathom_rebuild", command: str = "fathom rebuild"
) -> str:
    """A Dagster job file, one `@op` per batch with explicit `ins` for the wave edges.

    Dependencies are expressed through `ins` rather than `after`, because an op that
    merely runs later can still be reordered by a change nobody reviewed.
    """
    tasks = tasks_of(plan)
    lines = [
        _HEADER,
        "import subprocess",
        "",
        "from dagster import In, Nothing, job, op",
        "",
    ]
    if not tasks:
        lines += [f"@job(name={_quote(job_name)})", "def fathom_rebuild():", "    pass"]
        return "\n".join(lines) + "\n"

    for task in tasks:
        ins = (
            "{" + ", ".join(f"{_quote(u)}: In(Nothing)" for u in task.depends_on) + "}"
            if task.depends_on
            else "{}"
        )
        lines.append(f"@op(name={_quote(task.id)}, ins={ins})")
        lines.append(f"def {task.id}({', '.join(task.depends_on)}):")
        lines.append(f"    subprocess.run({_quote(task.shell(command))}, shell=True, check=True)")
        lines.append("")

    lines.append(f"@job(name={_quote(job_name)})")
    lines.append("def fathom_rebuild():")
    for task in tasks:
        args = ", ".join(f"{u}()" for u in task.depends_on)
        lines.append(f"    {task.id}({args})")
    return "\n".join(lines) + "\n"


def to_prefect(
    plan: Schedule, *, flow_name: str = "fathom-rebuild", command: str = "fathom rebuild"
) -> str:
    """A Prefect flow, using `wait_for` so wave boundaries are real dependencies."""
    tasks = tasks_of(plan)
    lines = [
        _HEADER,
        "import subprocess",
        "",
        "from prefect import flow, task",
        "",
        "@task",
        "def rebuild(command: str):",
        "    subprocess.run(command, shell=True, check=True)",
        "",
        f"@flow(name={_quote(flow_name)})",
        "def fathom_rebuild():",
    ]
    if not tasks:
        lines.append("    pass  # nothing to rebuild")
        return "\n".join(lines) + "\n"

    for task in tasks:
        wait = f", wait_for=[{', '.join(task.depends_on)}]" if task.depends_on else ""
        lines.append(f"    {task.id} = rebuild.submit({_quote(task.shell(command))}{wait})")
    return "\n".join(lines) + "\n"


def write_dag(plan: Schedule, *, flavor: str, command: str = "fathom rebuild") -> str:
    """Generate a DAG for one orchestrator, chosen by name."""
    if flavor == "airflow":
        return to_airflow(plan, command=command)
    if flavor == "dagster":
        return to_dagster(plan, command=command)
    if flavor == "prefect":
        return to_prefect(plan, command=command)
    raise ValueError(
        f"unknown orchestrator {flavor!r}; try one of ['airflow', 'dagster', 'prefect']"
    )
