"""Generated DAG files, and the two properties they must not lose.

A generated file that loses either is worse than no file: wave boundaries have to be
real dependencies, and partition keys have to travel with the task. Losing the first
rebuilds a downstream table from an upstream one that has not been written; losing the
second quietly full-rebuilds, which is the entire thing the plan existed to avoid.

Every generated file is also parsed with `ast`, because a generator that emits
syntactically invalid Python fails in someone's scheduler at 3am rather than here.
"""

from __future__ import annotations

import ast
from datetime import datetime

import pytest

from fathom.core.grains import Grain
from fathom.core.partitions import PartitionMapping
from fathom.core.types import DatasetId, KeyPredicate, PartitionField, PartitionSpec
from fathom.graph import Edge, Graph
from fathom.graph.plan import schedule as sched
from fathom.report import orchestrators

RAW = DatasetId("duckdb", "raw.events")
SILVER = DatasetId("duckdb", "silver.events")
GOLD = DatasetId("duckdb", "gold.monthly")

DAY = PartitionSpec.of(PartitionField.time("dt", Grain.DAY))
MONTH = PartitionSpec.of(PartitionField.time("dt", Grain.MONTH))

FLAVORS = ["airflow", "dagster", "prefect"]


@pytest.fixture
def graph() -> Graph:
    g = Graph()
    g.add_dataset(RAW, DAY)
    g.add_dataset(SILVER, DAY)
    g.add_dataset(GOLD, MONTH)
    g.add_edge(Edge(RAW, SILVER, PartitionMapping.identity(DAY), evidence="sql:1"))
    g.add_edge(Edge(SILVER, GOLD, PartitionMapping.rollup(DAY, MONTH), evidence="sql:2"))
    return g


@pytest.fixture
def plan(graph: Graph) -> sched.Schedule:
    days = [KeyPredicate.of(dt=datetime(2026, 3, d)) for d in (14, 15)]
    return sched.schedule(graph, graph.invalidate({RAW: days}))


@pytest.fixture
def empty_plan(graph: Graph) -> sched.Schedule:
    return sched.schedule(graph, graph.invalidate({}))


# -- typed tasks ---------------------------------------------------------------


def test_tasks_carry_their_partitions(plan):
    tasks = orchestrators.tasks_of(plan)
    assert tasks
    assert all(task.partitions for task in tasks)


def test_the_shell_line_names_the_partitions(plan):
    """A task that says 'rebuild gold.monthly' without saying which has lost the point."""
    task = orchestrators.tasks_of(plan)[0]
    line = task.shell("fathom rebuild")
    assert "--partitions" in line
    assert all(f"'{k}'" in line for k in task.partitions)


def test_later_waves_depend_on_earlier_ones(plan):
    tasks = orchestrators.tasks_of(plan)
    by_id = {t.id: t for t in tasks}
    assert any(t.depends_on for t in tasks), "a three-layer graph must produce a dependency"
    for task in tasks:
        for upstream in task.depends_on:
            assert upstream in by_id


# -- generated files parse -----------------------------------------------------


@pytest.mark.parametrize("flavor", FLAVORS)
def test_every_generated_file_is_valid_python(plan, flavor):
    """Otherwise it fails in someone's scheduler at 3am rather than here."""
    ast.parse(orchestrators.write_dag(plan, flavor=flavor))


@pytest.mark.parametrize("flavor", FLAVORS)
def test_an_empty_plan_still_generates_valid_python(empty_plan, flavor):
    source = orchestrators.write_dag(empty_plan, flavor=flavor)
    ast.parse(source)
    assert "nothing to rebuild" in source or "pass" in source


@pytest.mark.parametrize("flavor", FLAVORS)
def test_the_header_states_what_was_left_out(plan, flavor):
    source = orchestrators.write_dag(plan, flavor=flavor)
    assert "Generated by fathom" in source
    assert "real dependencies, not ordering hints" in source


@pytest.mark.parametrize("flavor", FLAVORS)
def test_partition_keys_reach_the_generated_file(plan, flavor):
    source = orchestrators.write_dag(plan, flavor=flavor)
    assert "--partitions" in source
    assert "2026-03-14" in source


@pytest.mark.parametrize("flavor", FLAVORS)
def test_the_command_is_the_callers_choice(plan, flavor):
    source = orchestrators.write_dag(plan, flavor=flavor, command="make rebuild")
    assert "make rebuild" in source


def test_an_unknown_flavor_names_the_ones_that_exist(plan):
    with pytest.raises(ValueError, match="airflow"):
        orchestrators.write_dag(plan, flavor="luigi")


# -- per-orchestrator shape ----------------------------------------------------


def test_airflow_uses_shift_operators_for_dependencies(plan):
    source = orchestrators.to_airflow(plan)
    assert ">>" in source
    assert "with DAG(" in source
    assert "from airflow.operators.bash import BashOperator" in source


def test_the_airflow_operator_can_be_swapped_and_the_import_follows(plan):
    source = orchestrators.to_airflow(plan, operator="HouseOperator")
    assert "from airflow.operators.bash import HouseOperator" in source
    assert "HouseOperator(" in source


def test_the_airflow_dag_id_is_the_callers_choice(plan):
    assert '"nightly"' in orchestrators.to_airflow(plan, dag_id="nightly")


def test_dagster_expresses_dependencies_as_ins_not_ordering(plan):
    """An op that merely runs later can be reordered by a change nobody reviewed."""
    source = orchestrators.to_dagster(plan)
    assert "In(Nothing)" in source
    assert "@op(" in source and "@job(" in source


def test_prefect_uses_wait_for(plan):
    source = orchestrators.to_prefect(plan)
    assert "wait_for=[" in source
    assert "rebuild.submit(" in source


def test_a_first_wave_task_has_no_dependency_clause(plan):
    source = orchestrators.to_prefect(plan)
    first = orchestrators.tasks_of(plan)[0]
    line = next(line for line in source.splitlines() if line.strip().startswith(first.id))
    assert "wait_for" not in line


# -- escaping ------------------------------------------------------------------


def test_a_dataset_name_with_a_quote_does_not_break_the_file(graph):
    """Identifiers are escaped, never trusted — the rule the rest of `report` follows."""
    awkward = DatasetId("duckdb", 'weird."name')
    g = Graph()
    g.add_dataset(awkward, DAY)
    g.add_dataset(GOLD, MONTH)
    g.add_edge(Edge(awkward, GOLD, PartitionMapping.rollup(DAY, MONTH), evidence="sql:1"))
    plan = sched.schedule(g, g.invalidate({awkward: [KeyPredicate.of(dt=datetime(2026, 3, 14))]}))

    for flavor in FLAVORS:
        ast.parse(orchestrators.write_dag(plan, flavor=flavor))
